stage: Don't stage base packages

diff --git a/stage b/stage
--- a/stage
+++ b/stage
@@ -1,28 +1,26 @@
 #!/bin/sh
 
-# send of list of ports to update to a build host
+# send list of installed ports to build host
 #
 # Usage: stage [-a]
 # -a: append to the list on the build server rather than overwriting
 #
 # globals expected in ${HOME}/.ports.conf with sample values
-# bhost='storage2.mathstat.dal.ca'  # build host
+# bhost='ser.ftfl.ca'  # build host
 # listf='ports.txt' # list file of ports to build, relative to $HOME
 
 . "$HOME/.ports.conf"
 
 stage () {
   hostname=$(hostname)
-  of="$(pkg info -oAq | \
+  of=$(pkg info -oAq | \
           awk -F'[[:blank:]]*:[[:blank:]]*' \
             '/^(Origin|flavor)/ {
-             if ( $1 == "Origin" ) {
-               if ( system("test -d /usr/ports/"$2) ) { io=1 }
-               else { io=0; print $2 }
-             }
-             else if ( $1 == "flavor" && !io && $2 != "default" ) { print "@"$2 }
-          }')"
+             if ($1 == "Origin" && $2 != "base") { print $2 }
+             if ($1 == "flavor" && $2 != "default") { print "@"$2 }
+          }')
   printf "%s\\n" "$of" | tr '\n' ' ' | sed 's/ @/@/g' | tr ' ' '\n' > "$listf"
+
   if [ "$hostname" != "$bhost" ]; then
     if [ "$1" = 'yes' ]; then
       #printf "Appending the list of ports to %s:%s...\\n" "$bhost" "$listf"
@@ -51,7 +49,7 @@ appendp=no
 while getopts ":a" opt; do
   case $opt in
     a) appendp=yes ;;
-    *) printf "Invalid option: -%s\\n." "$opt" ;;
+    *) printf "Invalid option: -%s\\n." "$opt"; exit 1 ;;
   esac
 done
 
